version: 2.1

workflows:
  testing:
    jobs:
      - runner-test

jobs:
  runner-test:
    machine: true
    resource_class: testing-namespace/resource_label
    steps:
      - run:
          name: Check Docker Version
          command: |
            echo "Checking Docker installation"
            docker --version

      - run:
          name: Pull Docker Image
          command: |
            echo "Pulling Nginx Docker image"
            docker pull nginx:latest

