version: 2.1

workflows:
  testing:
    jobs:
      - runner-test

jobs:
  runner-test:
    machine: true  # Use the machine executor for self-hosted runner
    resource_class: testing-namespace/resource_label  # Your custom resource class
    steps:
      - run:
          name: Create directory on the server
          command: |
            echo "Creating directory on the self-hosted runner"
            sudo mkdir -p /var/www/html/circleci  # Ensure the directory is created with proper permissions
