version: 2.1
jobs:
  runner-test:
    machine: true
    resource_class: testing-namespace/resource_label
    steps:
      - run:
          name: Add CircleCI User to Docker Group
          command: |
            sudo usermod -aG docker $USER
            sudo systemctl restart docker  # Restart Docker to apply group changes
      - run:
          name: Pull and Run Nginx Docker Image
          command: |
            docker pull nginx:latest

workflows:
  version: 2
  testing:
    jobs:
      - runner-test
