version: 2.1
jobs:
  runner-test:
    machine: true  # Specify if you're using the machine executor
    resource_class: large  # Choose a valid resource class, e.g., 'large'
    steps:
      - run:
          name: Echo a message
          command: echo "Hi I'm on Runners!"

workflows:
  version: 2
  testing:
    jobs:
      - runner-test
